apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging
  app.kubernetes.io/env: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: DeploymentConfig
      labelSelector: "app in (auth-service, grades-service, api-gateway)"
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5
    target:
      kind: HorizontalPodAutoscaler
