server:
  port: 8082

spring:
  application:
    name: grades-service

  datasource:
    url: jdbc:postgresql://192.168.1.83:5434/postgres
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  data:
    redis:
      host: 192.168.1.83
      port: 6379
      username: default
      password: mypassword
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

  cache:
    type: redis
    redis:
      time-to-live: 600000     # 10 minutes

app:
  jwt:
    secret: "3f8a2b1c9d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
