apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mytutorial

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - imagestreams.yaml
  - configmaps.yaml
  - deploymentconfigs.yaml
  - services.yaml
  - routes.yaml
  - hpas.yaml
  - pdbs.yaml
  - network-policies.yaml