apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-gateway
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    haproxy.router.openshift.io/timeout: 30s
spec:
  to:
    kind: Service
    name: api-gateway
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect